### PR TITLE
Added the first version of the NI Maschine MIDI config

### PR DESCRIPTION
**Pull request by HammyHavoc**
Hello Ryan!

Hope you are enjoying your weekend! :- )

This is a basic implementation of the recommendation of MIX, FM, Cutoff, Resonance, LFO Tune, and FM Freq Snap in place of VCF Volume for the time being just so we can get a working version in the repository so that the documentation doesn't lead to an empty directory.

I'm currently experimenting with a highly detailed version that utilizes far more of the MIDI CCs, though still trying to figure out the best method of organization and order to put them in that makes sense for performance and creation. Maschine utilizes banks/pages and you can name each knob, along with the page.

I'll continue to refine the more complex configuration and will await your thoughts re the issue I opened, that way I can carry on with the larger config. Not encountered any other issues yet.

### CODE REVIEW

**Comment by HammyHavoc** [comment]
Added that tweak to the firmware documentation. :- )

**Comment by raspy135** [comment]
I found a bug related to MIDI packet handling. It could be related to your CC# issue.
MIDI engine could be stopped if MIDI clock and Running status packet come at the same time.

I may push v1.50 firmware or 1.49 for the fix.

**Comment by HammyHavoc** [comment]
Excellent work! If you're happy to push a new firmware, I'm happy to flash the LyraT to it. :- )

**Comment by raspy135** [comment]
1.50 will introduce some features (Mostly for battery operation).
I rewrote UI logic to support this so I need extra time to verify. I hope I can release it in next few hours, I mean tonight in US.

**Comment by raspy135** [comment]
FYI I pushed v1.50 firmware.

**Pull request merged**
